<?php require __DIR__ . '/../layouts/header.php'; ?>
<div class="container-fluid">
  <?php if ($denied): ?><div class="alert alert-warning"><i class="fe fe-lock mr-2"></i> This resource is not available for the <?= htmlspecialchars(role_label()) ?> role.</div><?php endif; ?>
  <div class="row justify-content-center"><div class="col-12"><div class="row align-items-center mb-2"><div class="col"><h2 class="h5 page-title"><?= htmlspecialchars($title) ?></h2><p class="small text-muted mb-0"><?= htmlspecialchars($roleSubtitle) ?></p></div></div></div>
  <div class="col-12"><div class="row">
    <?php foreach ($metrics as $index => $metric): ?><div class="col-md-6 col-xl-3 mb-4"><div class="card shadow border-0 <?= $index === 2 ? 'bg-primary text-white' : '' ?>"><div class="card-body"><div class="row align-items-center"><div class="col-3 text-center"><span class="circle circle-sm <?= $index === 2 ? 'bg-primary-light' : 'bg-primary' ?>"><i class="fe fe-<?= htmlspecialchars($metric['icon']) ?> fe-16 text-white mb-0"></i></span></div><div class="col pr-0"><p class="small <?= $index === 2 ? 'text-white' : 'text-muted' ?> mb-0"><?= htmlspecialchars($metric['label']) ?></p><span class="h3 mb-0 <?= $index === 2 ? 'text-white' : '' ?>"><?= htmlspecialchars($metric['value']) ?></span><span class="small <?= $index === 2 ? 'text-white' : 'text-success' ?> ml-2"><?= htmlspecialchars($metric['trend']) ?></span></div></div></div></div></div><?php endforeach; ?>
  </div></div>
  <div class="col-12"><div class="row"><div class="col-md-8"><div class="card shadow"><div class="card-body"><table class="table table-hover logistics-data-table" style="font-size:11px"><thead><tr><th colspan="5">Recent Trips and Deliveries</th></tr><tr><th>#</th><th>Reference</th><th>Route</th><th>Vehicle / Driver</th><th>Status</th></tr></thead><tbody><?php foreach ($recentTrips as $index => $trip): ?><tr><td><?= $index + 1 ?></td><td><strong><?= htmlspecialchars($trip['reference']) ?></strong></td><td><?= htmlspecialchars($trip['route']) ?></td><td><?= htmlspecialchars($trip['vehicle'] . ' / ' . $trip['driver']) ?></td><td><span class="badge badge-light"><?= htmlspecialchars($trip['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div>
  <div class="col-md-4"><div class="card shadow eq-card timeline"><div class="card-header"><strong class="card-title">Operational attention</strong><a class="float-right small text-muted" href="#">Today</a></div><div class="card-body" data-simplebar style="height:360px;overflow-y:auto"><div class="pb-3 timeline-item"><span class="circle circle-sm bg-success h3 mb-0">1</span><div class="pl-5"><div class="mb-1 small"><strong>Vehicles due for service</strong></div><p class="small text-muted">2 vehicles require attention today.</p></div></div><div class="pb-3 timeline-item"><span class="circle circle-sm bg-warning h3 mb-0">2</span><div class="pl-5"><div class="mb-1 small"><strong>Licenses expiring soon</strong></div><p class="small text-muted">7 driver licenses expire within 30 days.</p></div></div><div class="pb-3 timeline-item"><span class="circle circle-sm bg-primary h3 mb-0">3</span><div class="pl-5"><div class="mb-1 small"><strong>Fuel consumption review</strong></div><p class="small text-muted">Monthly fleet fuel report is ready.</p></div></div></div></div></div></div></div>
</div>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
