<?php require __DIR__ . '/../layouts/header.php'; ?>
<div class="container-fluid">
  <div class="row justify-content-center"><div class="col-12">
    <?php if ($saved): ?><div class="alert alert-success"><i class="fe fe-check-circle mr-2"></i> Record submitted successfully. It is ready for review.</div><?php endif; ?>
    <?php if ($error === 'delete_reason'): ?><div class="alert alert-danger"><i class="fe fe-alert-circle mr-2"></i> A deletion reason is required before this record can be removed.</div><?php endif; ?>
    <?php if ($error === 'delete_failed'): ?><div class="alert alert-danger"><i class="fe fe-alert-circle mr-2"></i> This record is linked to other logistics data and cannot be deleted yet.</div><?php endif; ?>
    <?php if (!empty($errors ?? [])): ?><div class="alert alert-danger"><i class="fe fe-alert-circle mr-2"></i><strong>Please fix the following:</strong><ul class="mb-0 mt-2"><?php foreach ($errors as $message): ?><li><?= htmlspecialchars($message) ?></li><?php endforeach; ?></ul></div><?php endif; ?>
    <?php if ($action === 'details' && $record): ?>
      <div class="row align-items-center mb-3"><div class="col"><p class="small text-muted text-uppercase mb-1"><?= htmlspecialchars($module['kicker']) ?></p><h2 class="h5 page-title">Record details</h2></div><div class="col-auto"><a class="btn btn-outline-primary" href="<?= url($moduleKey) ?>">Back to list</a></div></div>
      <div class="card shadow"><div class="card-body"><div class="row"><div class="col-md-8"><h5><?= htmlspecialchars($record[0]) ?></h5><p class="text-muted">Complete record information and operational history.</p><dl class="row mt-4"><?php foreach ($module['columns'] as $index => $column): ?><dt class="col-sm-4 text-muted font-weight-normal"><?= htmlspecialchars($column) ?></dt><dd class="col-sm-8"><?= htmlspecialchars($record[$index] ?? '-') ?></dd><?php endforeach; ?></dl></div><div class="col-md-4"><div class="alert alert-light border"><strong>Available actions</strong><p class="small text-muted mt-2 mb-3">Update this record when the operational workflow changes.</p><a class="btn btn-primary btn-sm" href="<?= url([$moduleKey, $record[0], 'edit']) ?>">Edit record</a></div></div></div></div></div>
    <?php elseif ($action === 'edit' && $record): ?>
      <?php $formTitle = 'Edit ' . $record[0]; $formAction = url([$moduleKey, $record[0], 'edit']); ?>
      <?php require __DIR__ . '/form.php'; ?>
    <?php elseif ($action === 'create'): ?>
      <?php $formTitle = $module['button']; $formAction = url([$moduleKey, 'create']); $record = array_fill(0, count($module['columns']), ''); ?>
      <?php require __DIR__ . '/form.php'; ?>
    <?php else: ?>
      <div class="row align-items-center mb-2"><div class="col"><p class="small text-muted text-uppercase mb-1"><?= htmlspecialchars($module['kicker']) ?></p><h2 class="h5 page-title"><?= htmlspecialchars($module['title']) ?></h2><p class="text-muted small"><?= htmlspecialchars($module['description']) ?><?php if ($moduleKey === 'reports' && $reportType): ?> <span class="badge badge-light ml-2">Selected: <?= htmlspecialchars($reportType) ?></span><?php endif; ?></p></div><div class="col-auto"><?php if ($moduleKey === 'reports'): ?><a class="btn btn-outline-primary mr-2" href="<?= url(['reports', 'export'], $reportType ? ['report_type' => $reportType] : []) ?>"><i class="fe fe-download fe-12 mr-1"></i> Export CSV</a><?php endif; ?><a class="btn btn-primary" href="<?= url([$moduleKey, 'create']) ?>"><i class="fe fe-plus fe-12 mr-1"></i> <?= htmlspecialchars($module['button']) ?></a></div></div>
      <div class="card shadow"><div class="card-body"><div class="row mb-3"><div class="col-md-6"><input class="form-control module-search" placeholder="Search <?= strtolower(htmlspecialchars($module['title'])) ?>"></div><div class="col-md-3 ml-auto"><select class="form-control module-status-filter"><option value="">All statuses</option><option>Active</option><option>Pending</option><option>Completed</option><option>Approved</option><option>Available</option><option>In stock</option></select></div></div><table class="table table-hover logistics-data-table" style="font-size:12px"><thead><tr><?php foreach ($module['columns'] as $column): ?><th><?= htmlspecialchars($column) ?></th><?php endforeach; ?><th>Actions</th></tr></thead><tbody><?php foreach ($module['rows'] as $row): ?><tr><?php foreach ($row as $cell): ?><td><?= htmlspecialchars($cell) ?></td><?php endforeach; ?><td class="text-nowrap"><a href="<?= url([$moduleKey, $row[0]]) ?>" class="text-primary mr-2">View</a><?php if ($moduleKey === 'reports'): ?><a href="<?= url(['reports', 'export', $row[0]]) ?>" class="text-primary mr-2">Export</a><?php endif; ?><a href="<?= url([$moduleKey, $row[0], 'edit']) ?>" class="text-primary mr-2">Edit</a><?php if (in_array('Status', $module['columns'], true)): $statusIndex = array_search('Status', $module['columns'], true); $isOn = !in_array(strtolower((string) $row[$statusIndex]), ['inactive', 'off duty', 'cancelled'], true); ?><form method="post" action="<?= url([$moduleKey, $row[0], 'toggle']) ?>" class="d-inline switch-form"><input type="hidden" name="status" value="<?= $isOn ? '1' : '0' ?>"><div class="custom-control custom-switch d-inline-block mr-2 align-middle"><input type="checkbox" class="custom-control-input status-switch" aria-label="Toggle status for <?= htmlspecialchars($row[0]) ?>" id="switch-<?= htmlspecialchars(md5($moduleKey . $row[0])) ?>" <?= $isOn ? 'checked' : '' ?>><label class="custom-control-label" for="switch-<?= htmlspecialchars(md5($moduleKey . $row[0])) ?>"></label></div></form><?php endif; ?><form method="post" action="<?= url([$moduleKey, $row[0], 'delete']) ?>" class="d-inline delete-form"><input type="hidden" name="reason"><button class="btn btn-link btn-sm text-danger p-0" type="submit">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></div>
    <?php endif; ?>
  </div></div>
</div>
<?php require __DIR__ . '/../layouts/footer.php'; ?>
