  </main>
</div>
<script src="<?= $baseUrl ?>/assets/js/jquery.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/popper.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/moment.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/bootstrap.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/simplebar.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/daterangepicker.js"></script>
<script src="<?= $baseUrl ?>/assets/js/tinycolor-min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/config.js"></script>
<script src="<?= $baseUrl ?>/assets/js/apps.js"></script>
<script src="<?= $baseUrl ?>/assets/js/jquery.dataTables.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/dataTables.bootstrap4.min.js"></script>
<script src="<?= $baseUrl ?>/assets/js/select2.min.js"></script>
<div class="modal fade" id="statusConfirmModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Change status</h5><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><p class="mb-0">Confirm changing this record to <strong class="status-target">ON (1)</strong>?</p></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-primary" id="confirmStatusButton">Confirm change</button></div></div></div></div>
<div class="modal fade" id="deleteConfirmModal" tabindex="-1" role="dialog" aria-hidden="true"><div class="modal-dialog modal-dialog-centered" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Delete record</h5><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><p>Deletion is permanent. Enter a reason to continue.</p><label for="deleteReason">Reason</label><textarea class="form-control" id="deleteReason" rows="3" required></textarea><div class="invalid-feedback">A reason is required.</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Cancel</button><button type="button" class="btn btn-danger" id="confirmDeleteButton">Delete record</button></div></div></div></div>
<script>$(function(){ $('.select2').select2({theme:'bootstrap4',width:'100%'}); $('.logistics-data-table').each(function(){ var table=$(this).DataTable({autoWidth:true,lengthMenu:[[10,25,50,-1],[10,25,50,'All']]}); $('.module-search').on('keyup',function(){ table.search(this.value).draw(); }); $('.module-status-filter').on('change',function(){ table.search(this.value).draw(); }); }); var pendingStatusForm=null,pendingStatusValue=null,pendingDeleteForm=null; $('.status-switch').on('change',function(event){ event.preventDefault(); var input=$(this); pendingStatusValue=input.is(':checked') ? 1 : 0; input.prop('checked',!input.is(':checked')); pendingStatusForm=input.closest('form'); $('.status-target').text(pendingStatusValue ? 'ON (1)' : 'OFF (0)'); $('#statusConfirmModal').modal('show'); }); $('#confirmStatusButton').on('click',function(){ if(!pendingStatusForm){return;} pendingStatusForm.find('input[name=status]').val(pendingStatusValue); pendingStatusForm[0].submit(); }); $('#statusConfirmModal').on('hidden.bs.modal',function(){ pendingStatusForm=null; pendingStatusValue=null; }); $('.delete-form').on('submit',function(event){ event.preventDefault(); pendingDeleteForm=this; $('#deleteReason').val('').removeClass('is-invalid'); $('#deleteConfirmModal').modal('show'); }); $('#confirmDeleteButton').on('click',function(){ var reason=$('#deleteReason').val().trim(); if(!reason){ $('#deleteReason').addClass('is-invalid'); return; } $(pendingDeleteForm).find('input[name=reason]').val(reason); pendingDeleteForm.submit(); }); });</script>
</body>
</html>
